Changed 'scripts' and 'package.json' so they look like the ones in Dredd.

diff --git a/scripts/cov b/scripts/cov
--- a/scripts/cov
+++ b/scripts/cov
@@ -5,18 +5,25 @@
 # Example:
 # ./scripts/cov html-cov > cov.html
 
-rm -rf ./src-cov
-
-COV=./node_modules/coffee-coverage/bin/coffeecoverage
-MOCHA=./node_modules/mocha/bin/mocha
 
 REPORTER=$1
-echo "Using Mocha reporter: $REPORTER" 1>&2
-$COV --exclude node_modules,.git,test --path relative . ./src-cov 1>&2
-cp -r ./test ./src-cov/test
+echo "Using Mocha reporter: '$REPORTER'" 1>&2
+
+COV=./node_modules/coffee-coverage/bin/coffeecoverage
+MOCHA=./node_modules/.bin/mocha
+
+
+# Cleanup & preparation
+rm -rf ./src-cov
+mkdir ./src-cov
+
+# Creating directory with instrumented JS code
+$COV --exclude node_modules,.git,test --path=relative . ./src-cov 1>&2
 cp ./package.json ./src-cov
+cp -r ./test ./src-cov/test
 
-# Excluding test breaking coveralls report :( Reporting to coveralls.io for further investigation
-$MOCHA --reporter $REPORTER --recursive --timeout 120000 --compilers 'coffee:coffee-script/register' -i -g 'Using workaround for hooks in ruby' -i -g 'when using --server' -i -g 'Command line interface' './src-cov/test/**/*-test.coffee'
+# Testing
+find ./src-cov/test/ -name '*-test.coffee' | xargs "$MOCHA" --reporter="$REPORTER"
 
+# Output & cleanup
 rm -rf ./src-cov
